---
# handlers file for sendmail-smarthost
 - name: newaliases
   shell: newaliases

 - name: make install sendmail config files
   make: target=install chdir={{ mail_path }}
   when: ansible_os_family == 'FreeBSD'

 - name: restart sendmail
   make: target=restart-mta chdir={{ mail_path }}
   when: ansible_os_family == 'FreeBSD'

 - name: restart postfix
   service: name=postfix state=restarted
   when: ansible_os_family == 'RedHat'
